version: '3.7'
services:
  ucc_web:
    container_name: ucc
    build:
      context: .
      dockerfile: Dockerfile
    command: sh entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 9100:8000
    env_file:
      - .env.dev