# Generated by Django 4.0.7 on 2022-08-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo_abreviation',
            field=models.CharField(blank=True, max_length=5, verbose_name='logo abbreviation'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Logotype long'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Youtube video ID'),
        ),
    ]
