# Generated by Django 4.0.7 on 2022-08-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_logo_abreviation_homepage_logo_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_prologue',
            field=models.TextField(blank=True),
        ),
    ]
