# Generated by Django 4.0.7 on 2022-08-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_text_prologue'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_list_why_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_list_why_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_list_why_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_list_why_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_list_why_5',
            field=models.TextField(blank=True),
        ),
    ]
