# Generated by Django 4.0.7 on 2022-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_text_list_how_1_homepage_text_list_how_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_list_who_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_list_who_2',
            field=models.TextField(blank=True),
        ),
    ]
