# Generated by Django 4.0.7 on 2022-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_text_list_guiding_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_list_next',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_list_next_title',
            field=models.TextField(blank=True),
        ),
    ]
