# Generated by Django 4.0.7 on 2022-08-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_text_list_next_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_copyright',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_partners',
            field=models.TextField(blank=True),
        ),
    ]
