# Generated by Django 4.0.7 on 2022-08-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_text_media_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_list_guiding_header',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_list_why_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_prologue_title',
            field=models.TextField(blank=True),
        ),
    ]
