# Generated by Django 4.0.7 on 2022-08-11 11:10

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_text_list_how_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pic_media_about_1',
            field=models.FileField(blank=True, null=True, upload_to=home.models.file_path),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pic_media_about_2',
            field=models.FileField(blank=True, null=True, upload_to=home.models.file_path),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pic_media_about_3',
            field=models.FileField(blank=True, null=True, upload_to=home.models.file_path),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pic_media_about_title_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pic_media_about_title_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pic_media_about_title_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_media_about_pic_2',
            field=models.TextField(blank=True),
        ),
    ]
