# Generated by Django 4.0.7 on 2022-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_pic_media_about_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='link_media_about_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_media_about_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_media_about_3',
            field=models.URLField(blank=True),
        ),
    ]
