# Generated by Django 4.0.7 on 2022-08-23 13:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='guiding',
            field=wagtail.fields.StreamField([('text_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(help_text='Add your title', required=True)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.IntegerBlock(required=False)), ('title', wagtail.blocks.CharBlock(max_length=60, required=False)), ('description', wagtail.blocks.CharBlock(max_length=200, required=False))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
